<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f0b73775-0370-4efa-b435-27f6cd1db70a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new SpeedCalc where
		the mph is 99 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
